### ISSUE TITLE
input设置placeholder 颜色

### ISSUE THREAD

**Issue by lcl-101** [lcl-101/webpack-blog#34]
```css
input::-webkit-input-placeholder, textarea::-webkit-input-placeholder {
 color:    #ccc;
}
input:-moz-placeholder, textarea:-moz-placeholder {
 color:    #ccc;
}
input::-moz-placeholder, textarea::-moz-placeholder {
 color:    #ccc;
}
input:-ms-input-placeholder, textarea:-ms-input-placeholder {
 color:    #ccc;
}
```
